const firecrackerData = {
  sparklers: [
    {
      variety: "7CM ELECTRIC SPARKLERS",
      contents: "10 / BOX",
      rate_per_unit: 124.0,
      quantity: "10 BOXES",
      amount: 1240.0,
    },
    {
      variety: "10CM ELECTRIC SPARKLERS",
      contents: "10 / BOX",
      rate_per_unit: 111.0,
      quantity: "5 BOXES",
      amount: 555.0,
    },
    {
      variety: "15CM ELECTRIC SPARKLERS",
      contents: "10 / BOX",
      rate_per_unit: 111.0,
      quantity: "2 BOXES",
      amount: 222.0,
    },
    {
      variety: "30CM ELECTRIC SPARKLERS",
      contents: "5 / BOX",
      rate_per_unit: 111.0,
      quantity: "2 BOXES",
      amount: 222.0,
    },
    {
      variety: "50CM ELECTRIC SPARKLERS",
      contents: "5 / BOX",
      rate_per_unit: 195.0,
      quantity: "1 BOX",
      amount: 195.0,
    },
    {
      variety: "10CM COLOR SPARKLERS",
      contents: "10 / BOX",
      rate_per_unit: 137.0,
      quantity: "5 BOXES",
      amount: 685.0,
    },
    {
      variety: "15CM COLOR SPARKLERS",
      contents: "10 / BOX",
      rate_per_unit: 117.0,
      quantity: "2 BOXES",
      amount: 234.0,
    },
    {
      variety: "30CM COLOR SPARKLERS",
      contents: "5 / BOX",
      rate_per_unit: 117.0,
      quantity: "2 BOXES",
      amount: 234.0,
    },
    {
      variety: "50CM COLOR SPARKLERS",
      contents: "5 / BOX",
      rate_per_unit: 221.0,
      quantity: "1 BOX",
      amount: 221.0,
    },
    {
      variety: "7CM GREEN SPARKLERS",
      contents: "10 / BOX",
      rate_per_unit: 156.0,
      quantity: "10 BOXES",
      amount: 1560.0,
    },
    {
      variety: "10CM GREEN SPARKLERS",
      contents: "10 / BOX",
      rate_per_unit: 137.0,
      quantity: "5 BOXES",
      amount: 685.0,
    },
    {
      variety: "15CM GREEN SPARKLERS",
      contents: "10 / BOX",
      rate_per_unit: 117.0,
      quantity: "2 BOXES",
      amount: 234.0,
    },
    {
      variety: "30CM GREEN SPARKLERS",
      contents: "5 / BOX",
      rate_per_unit: 117.0,
      quantity: "2 BOXES",
      amount: 234.0,
    },
    {
      variety: "50CM GREEN SPARKLERS",
      contents: "5 / BOX",
      rate_per_unit: 208.0,
      quantity: "1 BOX",
      amount: 208.0,
    },
    {
      variety: "7CM RED SPARKLERS",
      contents: "10 / BOX",
      rate_per_unit: 182.0,
      quantity: "10 BOXES",
      amount: 1820.0,
    },
    {
      variety: "10CM RED SPARKLERS",
      contents: "10 / BOX",
      rate_per_unit: 156.0,
      quantity: "5 BOXES",
      amount: 780.0,
    },
    {
      variety: "15CM RED SPARKLERS",
      contents: "10 / BOX",
      rate_per_unit: 130.0,
      quantity: "2 BOXES",
      amount: 260.0,
    },
    {
      variety: "30CM RED SPARKLERS",
      contents: "5 / BOX",
      rate_per_unit: 130.0,
      quantity: "2 BOXES",
      amount: 260.0,
    },
  ],
  chakkars: [
    {
      variety: "GROUND CHAKKAR BIG",
      contents: "10 / BOX",
      rate_per_unit: 46.0,
      quantity: "1 BOX",
      amount: 46.0,
    },
    {
      variety: "GROUND CHAKKAR ASOKA",
      contents: "10 / BOX",
      rate_per_unit: 71.0,
      quantity: "1 BOX",
      amount: 71.0,
    },
    {
      variety: "GROUND CHAKKAR SPECIAL",
      contents: "10 / BOX",
      rate_per_unit: 86.0,
      quantity: "1 BOX",
      amount: 86.0,
    },
    {
      variety: "GROUND CHAKKAR DELUXE",
      contents: "10 / BOX",
      rate_per_unit: 169.0,
      quantity: "1 BOX",
      amount: 169.0,
    },
    {
      variety: "SPIN MASTER MAX RED & GREEN",
      contents: "10 / BOX",
      rate_per_unit: 176.0,
      quantity: "1 BOX",
      amount: 176.0,
    },
  ],
  flower_pots: [
    {
      variety: "FLOWER POT BIG",
      contents: "10 / BOX",
      rate_per_unit: 104.0,
      quantity: "1 BOX",
      amount: 104.0,
    },
    {
      variety: "FLOWER POT SPECIAL",
      contents: "10 / BOX",
      rate_per_unit: 150.0,
      quantity: "1 BOX",
      amount: 150.0,
    },
    {
      variety: "FLOWER POTS ASHOKA",
      contents: "10 / BOX",
      rate_per_unit: 228.0,
      quantity: "1 BOX",
      amount: 228.0,
    },
    {
      variety: "FLOWER POTS SURAJ/GIANT",
      contents: "10 / BOX",
      rate_per_unit: 299.0,
      quantity: "1 BOX",
      amount: 299.0,
    },
    {
      variety: "FLOWER POTS SPECIAL GREEN",
      contents: "10 / BOX",
      rate_per_unit: 150.0,
      quantity: "1 BOX",
      amount: 150.0,
    },
    {
      variety: "FLOWER POT ASOKA GREEN",
      contents: "10 / BOX",
      rate_per_unit: 228.0,
      quantity: "1 BOX",
      amount: 228.0,
    },
    {
      variety: "COLOUR CHANGING FLOWERS",
      contents: "3 / BOX",
      rate_per_unit: 189.0,
      quantity: "1 BOX",
      amount: 189.0,
    },
    {
      variety: "COLOUR KOTI DELUXE",
      contents: "5 / BOX",
      rate_per_unit: 247.0,
      quantity: "1 BOX",
      amount: 247.0,
    },
    {
      variety: "COLOUR KOTI DELUXE",
      contents: "10 / BOX",
      rate_per_unit: 455.0,
      quantity: "1 BOX",
      amount: 455.0,
    },
    {
      variety: "COLOUR KOTI SUPER DELUXE (UV BOX)",
      contents: "10 / BOX",
      rate_per_unit: 559.0,
      quantity: "1 BOX",
      amount: 559.0,
    },
    {
      variety: "PEACOCK DANCE/GOLDEN ASHRAFI",
      contents: "1's BOX",
      rate_per_unit: 137.0,
      quantity: "1 BOX",
      amount: 137.0,
    },
  ],
  twinkling_star_and_pencil_varieties: [
    {
      variety: 'TWINKLING STAR MEDIUM 1 1/2"',
      contents: "10 / BOX",
      rate_per_unit: 38.0,
      quantity: "1 BOX",
      amount: 38.0,
    },
    {
      variety: "TWINKLING STAR DELUXE 4'",
      contents: "10 / BOX",
      rate_per_unit: 104.0,
      quantity: "1 BOX",
      amount: 104.0,
    },
    {
      variety: "MAGIC PENCIL FOILS",
      contents: "10 / BOX",
      rate_per_unit: 42.0,
      quantity: "1 BOX",
      amount: 42.0,
    },
    {
      variety: "DELIGHT CANDLES",
      contents: "10 / BOX",
      rate_per_unit: 85.0,
      quantity: "1 BOX",
      amount: 85.0,
    },
    {
      variety: "SMART CANDLE (CRACKLING)",
      contents: "2 / BOX",
      rate_per_unit: 74.0,
      quantity: "1 BOX",
      amount: 74.0,
    },
    {
      variety: "SMART CANDLE (CRACKLING)",
      contents: "10 / BOX",
      rate_per_unit: 371.0,
      quantity: "1 BOX",
      amount: 371.0,
    },
    {
      variety: "WOLVERINE (Golden)",
      contents: "2 / BOX",
      rate_per_unit: 156.0,
      quantity: "1 BOX",
      amount: 156.0,
    },
    {
      variety: "PENCIL COLOUR",
      contents: "10/BOX",
      rate_per_unit: 98.0,
      quantity: "1 BOX",
      amount: 98.0,
    },
  ],
  single_shot_and_bombs: [
    {
      variety: '3 1/2" LAKSHMI',
      contents: "5s pkt",
      rate_per_unit: 14.0,
      quantity: "10 PKT",
      amount: 140.0,
    },
    {
      variety: '3 1/2" DLX LAKSHMI',
      contents: "5s pkt",
      rate_per_unit: 21.0,
      quantity: "1 PKT",
      amount: 21.0,
    },
    {
      variety: '4" LAKSHMI',
      contents: "5s pkt",
      rate_per_unit: 26.0,
      quantity: "1 PKT",
      amount: 26.0,
    },
    {
      variety: '4 " DLX LAKSHMI',
      contents: "5s pkt",
      rate_per_unit: 31.0,
      quantity: "1 PKT",
      amount: 31.0,
    },
    {
      variety: "TWO SOUND",
      contents: "5s pkt",
      rate_per_unit: 30.0,
      quantity: "1 PKT",
      amount: 30.0,
    },
    {
      variety: "TWO SOUND WITH GREEN COLOUR",
      contents: "5s pkt",
      rate_per_unit: 61.0,
      quantity: "1 PKT",
      amount: 61.0,
    },
  ],
  bombs: [
    {
      variety: "HYDRO BOMB SUPER /MINI GYPSY",
      contents: "10 / BOX",
      rate_per_unit: 81.0,
      quantity: "1 BOX",
      amount: 81.0,
    },
    {
      variety: "GYPSY BOMB GREEN",
      contents: "10 / BOX",
      rate_per_unit: 150.0,
      quantity: "1 BOX",
      amount: 150.0,
    },
    {
      variety: "KILLER BOMB DELUXE SIZE- 7 PLY",
      contents: "10 / BOX",
      rate_per_unit: 241.0,
      quantity: "1 BOX",
      amount: 241.0,
    },
    {
      variety: "BULLET BOMB FOILS",
      contents: "10 / BOX",
      rate_per_unit: 49.0,
      quantity: "1 BOX",
      amount: 49.0,
    },
    {
      variety: "BULLET BOMB DELUXE FOILS",
      contents: "10 / BOX",
      rate_per_unit: 60.0,
      quantity: "1 BOX",
      amount: 60.0,
    },
  ],
  chorsa_crackers: [
    {
      variety: "BIJILI CRACKERS RED",
      contents: "100/BAG",
      rate_per_unit: 46.0,
      quantity: "1 BAG",
      amount: 46.0,
    },
    {
      variety: "BIJILI CRACKERS RED MINI",
      contents: "50 / BAG",
      rate_per_unit: 26.0,
      quantity: "1 BAG",
      amount: 26.0,
    },
  ],
  new_varieties: [
    {
      variety: "DRONE",
      contents: "5's Box",
      rate_per_unit: 202.0,
      quantity: "1 BOX",
      amount: 202.0,
    },
    {
      variety: "Helicpoter with wngs",
      contents: "5 Pcs",
      rate_per_unit: 130.0,
      quantity: "1 Box",
      amount: 130.0,
    },
    {
      variety: "Spinner / Bambara",
      contents: "10 Pcs",
      rate_per_unit: 143.0,
      quantity: "1 Box",
      amount: 143.0,
    },
    {
      variety: "Money in the Bank (Fountains Money)",
      contents: "3's Box",
      rate_per_unit: 195.0,
      quantity: "1 Box",
      amount: 195.0,
    },
    {
      variety: "Lotus wheel (Wheel with colour Fountain)",
      contents: "5's Box",
      rate_per_unit: 150.0,
      quantity: "1 Box",
      amount: 150.0,
    },
    {
      variety: "4 x 4 Wheel (with Flower Show)",
      contents: "5's Box",
      rate_per_unit: 195.0,
      quantity: "1 Box",
      amount: 195.0,
    },
    {
      variety: "Top Gun +27 (Crackling Gun)",
      contents: "5's Box",
      rate_per_unit: 286.0,
      quantity: "1 Box",
      amount: 286.0,
    },
    {
      variety: "Musical Rocket (Aerial Music)",
      contents: "5's Box",
      rate_per_unit: 130.0,
      quantity: "1 Box",
      amount: 130.0,
    },
    {
      variety: "Maurai Malli (White fountain)",
      contents: "3's Box",
      rate_per_unit: 228.0,
      quantity: "1 Box",
      amount: 228.0,
    },
    {
      variety: "Old is Gold (ola vedi)",
      contents: "25's Box",
      rate_per_unit: 205.0,
      quantity: "1 Box",
      amount: 205.0,
    },
    {
      variety: "90 watts (Crackling)",
      contents: "3's Box",
      rate_per_unit: 163.0,
      quantity: "1 Box",
      amount: 163.0,
    },
    {
      variety: "Emu Egg (Fountain & Balloon)",
      contents: "2's Box",
      rate_per_unit: 195.0,
      quantity: "1 Box",
      amount: 195.0,
    },
    {
      variety: "Colour changing Butterfly",
      contents: "10's Box",
      rate_per_unit: 150.0,
      quantity: "1 Box",
      amount: 150.0,
    },
    {
      variety: "colour smoke (Yellow,orange&Blue)",
      contents: "3's Box",
      rate_per_unit: 228.0,
      quantity: "1 Box",
      amount: 228.0,
    },
    {
      variety: "SIVAKASI SPECIAL (Multi Color Fountain)",
      contents: "2's Box",
      rate_per_unit: 228.0,
      quantity: "1 Box",
      amount: 228.0,
    },
    {
      variety: "SHIN CHAN(Multi color Fountain)",
      contents: "5's Box",
      rate_per_unit: 111.0,
      quantity: "1 Box",
      amount: 111.0,
    },
    {
      variety: "PLANET WHEELER SHOW (CRACKLING)",
      contents: "2's Box",
      rate_per_unit: 241.0,
      quantity: "1 Box",
      amount: 241.0,
    },
    {
      variety: "DORA",
      contents: "5's Box",
      rate_per_unit: 156.0,
      quantity: "1 Box",
      amount: 156.0,
    },
    {
      variety: '6" WATER QUEEN',
      contents: "1's Box",
      rate_per_unit: 221.0,
      quantity: "1 Box",
      amount: 221.0,
    },
    {
      variety: "PHOTO FLASH",
      contents: "5's Box",
      rate_per_unit: 114.0,
      quantity: "1 Box",
      amount: 114.0,
    },
  ],
  rockets: [
    {
      variety: "ROCKET BOMB",
      contents: "10 / BOX",
      rate_per_unit: 81.0,
      quantity: "1 BOX",
      amount: 81.0,
    },
    {
      variety: "WHISTLING ROCKET",
      contents: "10 / BOX",
      rate_per_unit: 260.0,
      quantity: "1 BOX",
      amount: 260.0,
    },
  ],
  small_fancy_items: [
    {
      variety: "Chitput (Crackling)",
      contents: "10 / BOX",
      rate_per_unit: 35.0,
      quantity: "1 BOX",
      amount: 35.0,
    },
    {
      variety: "Crazy kids",
      contents: "10 / BOX",
      rate_per_unit: 87.0,
      quantity: "1 box",
      amount: 87.0,
    },
    {
      variety: "Seven shot with colour",
      contents: "3's Pkt",
      rate_per_unit: 91.0,
      quantity: "1 pkt",
      amount: 91.0,
    },
    {
      variety: "Seven shot with colour",
      contents: "6's Box",
      rate_per_unit: 182.0,
      quantity: "1 BOX",
      amount: 182.0,
    },
    {
      variety: "7 SHOT COLOUR",
      contents: "5'SBOX",
      rate_per_unit: 152.0,
      quantity: "1BOX",
      amount: 152.0,
    },
    {
      variety: "Emerald stone Green",
      contents: "10's Box",
      rate_per_unit: 55.0,
      quantity: "1 BOX",
      amount: 55.0,
    },
  ],
  fancy_fountains: [
    {
      variety: "MULTI COLOUR FOUNTAIN (4 varities)",
      contents: "5 / BOX",
      rate_per_unit: 98.0,
      quantity: "1 BOX",
      amount: 98.0,
    },
    {
      variety: "POPS AND DROPS(5 COLORS)",
      contents: "5 / BOX",
      rate_per_unit: 169.0,
      quantity: "1 BOX",
      amount: 169.0,
    },
    {
      variety: "MY QUEEN (CRACKLING)",
      contents: "1 / BOX",
      rate_per_unit: 134.0,
      quantity: "1 BOX",
      amount: 134.0,
    },
    {
      variety: "ROYAL RED COLOUR & CRACKLING",
      contents: "1 / BOX",
      rate_per_unit: 134.0,
      quantity: "1 BOX",
      amount: 134.0,
    },
    {
      variety: "ROYAL GREEN COLOUR & CRACKLING",
      contents: "1 / BOX",
      rate_per_unit: 134.0,
      quantity: "1 BOX",
      amount: 134.0,
    },
    {
      variety: "ROYAL GOLD COLOUR & CRACKLING",
      contents: "1 / BOX",
      rate_per_unit: 134.0,
      quantity: "1 BOX",
      amount: 134.0,
    },
    {
      variety: "ROYAL SILVER COLOUR & CRACKLING",
      contents: "1 / BOX",
      rate_per_unit: 134.0,
      quantity: "1 BOX",
      amount: 134.0,
    },
    {
      variety: "COCKTAIL(MULTI COLOR)",
      contents: "3/BOX",
      rate_per_unit: 137.0,
      quantity: "1 BOX",
      amount: 137.0,
    },
    {
      variety: "GOLD RUSH",
      contents: "3/BOX",
      rate_per_unit: 137.0,
      quantity: "1 BOX",
      amount: 137.0,
    },
    {
      variety: "MAGIC TREE",
      contents: "3/BOX",
      rate_per_unit: 137.0,
      quantity: "1 BOX",
      amount: 137.0,
    },
    {
      variety: "GOLDEN ASHRAFI",
      contents: "3/BOX",
      rate_per_unit: 169.0,
      quantity: "1 BOX",
      amount: 169.0,
    },
    {
      variety: "ASHRAFI COTI",
      contents: "3/BOX",
      rate_per_unit: 169.0,
      quantity: "1 BOX",
      amount: 169.0,
    },
    {
      variety: "X-MAS TREE",
      contents: "3/BOX",
      rate_per_unit: 169.0,
      quantity: "1 BOX",
      amount: 169.0,
    },
    {
      variety: "CRACKLING DIAMOND",
      contents: "1 / BOX",
      rate_per_unit: 195.0,
      quantity: "1 BOX",
      amount: 195.0,
    },
    {
      variety: "GLITTERING FLOWERS",
      contents: "1 / BOX",
      rate_per_unit: 195.0,
      quantity: "1 BOX",
      amount: 195.0,
    },
    {
      variety: "FLY BEES RED",
      contents: "1 / BOX",
      rate_per_unit: 195.0,
      quantity: "1 BOX",
      amount: 195.0,
    },
    {
      variety: "FLY BEES YELLOW",
      contents: "1 / BOX",
      rate_per_unit: 195.0,
      quantity: "1 BOX",
      amount: 195.0,
    },
    {
      variety: "POPCORN YELLOW",
      contents: "2/BOX",
      rate_per_unit: 273.0,
      quantity: "1 BOX",
      amount: 273.0,
    },
    {
      variety: "POPCORN WHITE",
      contents: "2/BOX",
      rate_per_unit: 273.0,
      quantity: "1 BOX",
      amount: 273.0,
    },
    {
      variety: "OREO CHOCO(GOLDEN SHOWER WITH COLOUR BALLS)",
      contents: "1/BOX",
      rate_per_unit: 137.0,
      quantity: "1 BOX",
      amount: 137.0,
    },
    {
      variety: "OREO STRAWBERRY",
      contents: "1/BOX",
      rate_per_unit: 137.0,
      quantity: "1 BOX",
      amount: 137.0,
    },
    {
      variety: "OREO LEMON",
      contents: "1/BOX",
      rate_per_unit: 137.0,
      quantity: "1 BOX",
      amount: 137.0,
    },
    {
      variety: "OREO MINT",
      contents: "1/BOX",
      rate_per_unit: 137.0,
      quantity: "1 BOX",
      amount: 137.0,
    },
    {
      variety: "OREO RED VELVET",
      contents: "1/BOX",
      rate_per_unit: 137.0,
      quantity: "1 BOX",
      amount: 137.0,
    },
    {
      variety: "OREO SPRING",
      contents: "1/BOX",
      rate_per_unit: 137.0,
      quantity: "1 BOX",
      amount: 137.0,
    },
    {
      variety: "SUNRISE 2G (3FOUNTAINS in V SHAPE)",
      contents: "1/BOX",
      rate_per_unit: 312.0,
      quantity: "1 BOX",
      amount: 312.0,
    },
    {
      variety: "PEACOCK DANCE (MULTI COLOR)",
      contents: "1/BOX",
      rate_per_unit: 202.0,
      quantity: "1 BOX",
      amount: 202.0,
    },
    {
      variety: "PEACOCK DANCE (MULTI COLOR-LARGE SIZE)",
      contents: "1/BOX",
      rate_per_unit: 351.0,
      quantity: "1 BOX",
      amount: 351.0,
    },
    {
      variety: "HEERA MOTI(FULL CRACKLING+GLITTERING FOUNTAIN)",
      contents: "3 / BOX",
      rate_per_unit: 394.0,
      quantity: "1 BOX",
      amount: 394.0,
    },
  ],
  whistling_items: [
    {
      variety: "SIREN THRILLER BIG",
      contents: "2 / BOX",
      rate_per_unit: 221.0,
      quantity: "1 BOX",
      amount: 221.0,
    },
    {
      variety: "WHISTLING WHEEL",
      contents: "5 / BOX",
      rate_per_unit: 169.0,
      quantity: "1 BOX",
      amount: 169.0,
    },
    {
      variety: "WHISTLING MULTIPLE 6 SHOT",
      contents: "1 / BOX",
      rate_per_unit: 306.0,
      quantity: "1 BOX",
      amount: 306.0,
    },
  ],
  fancy_aerial_shots: [
    {
      variety: 'CHINY CHICKS 6.75" X 0.75" (5 Variety)',
      contents: "10'S BOX",
      rate_per_unit: 429.0,
      quantity: "1 BOX",
      amount: 429.0,
    },
    {
      variety: "Gold Fish",
      contents: "2/BOX",
      rate_per_unit: 88.0,
      quantity: "1 BOX",
      amount: 88.0,
    },
    {
      variety: "Silver Falls",
      contents: "2/BOX",
      rate_per_unit: 88.0,
      quantity: "1 BOX",
      amount: 88.0,
    },
    {
      variety: "Bingo Green",
      contents: "2/BOX",
      rate_per_unit: 88.0,
      quantity: "1 BOX",
      amount: 88.0,
    },
    {
      variety: "Red Monster",
      contents: "2/BOX",
      rate_per_unit: 88.0,
      quantity: "1 BOX",
      amount: 88.0,
    },
    {
      variety: "Rainbow Dreams",
      contents: "2/BOX",
      rate_per_unit: 88.0,
      quantity: "1 BOX",
      amount: 88.0,
    },
    {
      variety: '7" X 1 1/4" PENTA SKY FIVE COLOR SHOTS+CRACKLING',
      contents: "5/BOX",
      rate_per_unit: 195.0,
      quantity: "1 BOX",
      amount: 195.0,
    },
    {
      variety: '8" x 1" CHOTTA FANCY',
      contents: "1'S BOX",
      rate_per_unit: 83.0,
      quantity: "1 BOX",
      amount: 83.0,
    },
    {
      variety: '8" x 1" CHOTTA FANCY',
      contents: "5's BOX",
      rate_per_unit: 416.0,
      quantity: "1 BOX",
      amount: 416.0,
    },
  ],
  pipe_13_x_2_25_multicolour: [
    {
      variety: "Star war crackling",
      contents: "1 / BOX",
      rate_per_unit: 182.0,
      quantity: "1 BOX",
      amount: 182.0,
    },
    {
      variety: "Star Platina -yellow crackling",
      contents: "1 / BOX",
      rate_per_unit: 182.0,
      quantity: "1 BOX",
      amount: 182.0,
    },
    {
      variety: "Star Janani-Green crackling",
      contents: "1 / BOX",
      rate_per_unit: 182.0,
      quantity: "1 BOX",
      amount: 182.0,
    },
    {
      variety: "Star Meghdot-Red crackling",
      contents: "1 / BOX",
      rate_per_unit: 182.0,
      quantity: "1 BOX",
      amount: 182.0,
    },
  ],
  pipe_12_x_2_multicolour: [
    {
      variety: "BOOMER",
      contents: "1 / BOX",
      rate_per_unit: 185.0,
      quantity: "1 BOX",
      amount: 185.0,
    },
    {
      variety: "MOTHI MAHAL",
      contents: "1 / BOX",
      rate_per_unit: 185.0,
      quantity: "1 BOX",
      amount: 185.0,
    },
    {
      variety: "GOLDEN ANGELS",
      contents: "1/BOX",
      rate_per_unit: 185.0,
      quantity: "1 BOX",
      amount: 185.0,
    },
    {
      variety: "PALM TREE",
      contents: "1/BOX",
      rate_per_unit: 185.0,
      quantity: "1 BOX",
      amount: 185.0,
    },
    {
      variety: "GARAM MASALA",
      contents: "1/BOX",
      rate_per_unit: 185.0,
      quantity: "1 BOX",
      amount: 185.0,
    },
  ],
  planet_series_15_x_3: [
    {
      variety: "SUN",
      contents: "1'S BOX",
      rate_per_unit: 312.0,
      quantity: "1 BOX",
      amount: 312.0,
    },
    {
      variety: "VENUS",
      contents: "1'S BOX",
      rate_per_unit: 312.0,
      quantity: "1 BOX",
      amount: 312.0,
    },
    {
      variety: "PLUTO",
      contents: "1'S BOX",
      rate_per_unit: 312.0,
      quantity: "1 BOX",
      amount: 312.0,
    },
    {
      variety: "NEPTUNE",
      contents: "1'S BOX",
      rate_per_unit: 312.0,
      quantity: "1 BOX",
      amount: 312.0,
    },
    {
      variety: "EARTH",
      contents: "1'S BOX",
      rate_per_unit: 312.0,
      quantity: "1 BOX",
      amount: 312.0,
    },
    {
      variety: "MARS",
      contents: "1'S BOX",
      rate_per_unit: 312.0,
      quantity: "1 BOX",
      amount: 312.0,
    },
    {
      variety: "JUPITER",
      contents: "1'S BOX",
      rate_per_unit: 312.0,
      quantity: "1 BOX",
      amount: 312.0,
    },
    {
      variety: "MERCURY",
      contents: "1'S BOX",
      rate_per_unit: 312.0,
      quantity: "1 BOX",
      amount: 312.0,
    },
    {
      variety: "MOON",
      contents: "1'S BOX",
      rate_per_unit: 312.0,
      quantity: "1 BOX",
      amount: 312.0,
    },
  ],
  sky_divers_3_5: [
    {
      variety: "BIG BOSS",
      contents: "1'S BOX",
      rate_per_unit: 481.0,
      quantity: "1 BOX",
      amount: 481.0,
    },
    {
      variety: "COOL COLOURS",
      contents: "1'S BOX",
      rate_per_unit: 481.0,
      quantity: "1 BOX",
      amount: 481.0,
    },
    {
      variety: "GOLD KING",
      contents: "1'S BOX",
      rate_per_unit: 481.0,
      quantity: "1 BOX",
      amount: 481.0,
    },
    {
      variety: "ROCK MY WORLD",
      contents: "1'S BOX",
      rate_per_unit: 481.0,
      quantity: "1 BOX",
      amount: 481.0,
    },
    {
      variety: "STREET FIGHTER",
      contents: "1'S BOX",
      rate_per_unit: 481.0,
      quantity: "1 BOX",
      amount: 481.0,
    },
    {
      variety: "TOMB RAIDER",
      contents: "1'S BOX",
      rate_per_unit: 481.0,
      quantity: "1 BOX",
      amount: 481.0,
    },
    {
      variety: "FANTA",
      contents: "1'S BOX",
      rate_per_unit: 481.0,
      quantity: "1 BOX",
      amount: 481.0,
    },
    {
      variety: "HOT CHIPS",
      contents: "1'S BOX",
      rate_per_unit: 481.0,
      quantity: "1 BOX",
      amount: 481.0,
    },
    {
      variety: "GOLD EYE CRACKLING",
      contents: "1'S BOX",
      rate_per_unit: 481.0,
      quantity: "1 BOX",
      amount: 481.0,
    },
    {
      variety: "GOLD EYE WHITE",
      contents: "1'S BOX",
      rate_per_unit: 481.0,
      quantity: "1 BOX",
      amount: 481.0,
    },
    {
      variety: "GOLD EYE GREEN",
      contents: "1'S BOX",
      rate_per_unit: 481.0,
      quantity: "1 BOX",
      amount: 481.0,
    },
    {
      variety: "GOLD EYE RED",
      contents: "1'S BOX",
      rate_per_unit: 481.0,
      quantity: "1 BOX",
      amount: 481.0,
    },
  ],
  seven_wonders: [
    {
      variety: "LIBERTY",
      contents: "1/BOX",
      rate_per_unit: 455.0,
      quantity: "1 BOX",
      amount: 455.0,
    },
    {
      variety: "PYRAMID",
      contents: "1/BOX",
      rate_per_unit: 455.0,
      quantity: "1 BOX",
      amount: 455.0,
    },
    {
      variety: "GREAT WALL",
      contents: "1/BOX",
      rate_per_unit: 455.0,
      quantity: "1 BOX",
      amount: 455.0,
    },
    {
      variety: "EIFFEL TOWER",
      contents: "1/BOX",
      rate_per_unit: 455.0,
      quantity: "1 BOX",
      amount: 455.0,
    },
    {
      variety: "PISA",
      contents: "1/BOX",
      rate_per_unit: 455.0,
      quantity: "1 BOX",
      amount: 455.0,
    },
    {
      variety: "TAJMAHAL",
      contents: "1/BOX",
      rate_per_unit: 455.0,
      quantity: "1 BOX",
      amount: 455.0,
    },
    {
      variety: "MACHU PICHHU",
      contents: "1/BOX",
      rate_per_unit: 455.0,
      quantity: "1 BOX",
      amount: 455.0,
    },
  ],
  unique_shells_2_pieces_mix: [
    {
      variety: "BLUEBERRY",
      contents: "2/BOX",
      rate_per_unit: 1333.0,
      quantity: "1 BOX",
      amount: 1333.0,
    },
    {
      variety: "MISS UNIVERSE",
      contents: "2/BOX",
      rate_per_unit: 1333.0,
      quantity: "1 BOX",
      amount: 1333.0,
    },
    {
      variety: "BLACK THUNDER",
      contents: "2/BOX",
      rate_per_unit: 1333.0,
      quantity: "1 BOX",
      amount: 1333.0,
    },
    {
      variety: "CRAZY BOYS",
      contents: "2/BOX",
      rate_per_unit: 1333.0,
      quantity: "1 BOX",
      amount: 1333.0,
    },
    {
      variety: "KRACK JACK",
      contents: "2/BOX",
      rate_per_unit: 1333.0,
      quantity: "1 BOX",
      amount: 1333.0,
    },
    {
      variety: "ACE",
      contents: "2/BOX",
      rate_per_unit: 1333.0,
      quantity: "1 BOX",
      amount: 1333.0,
    },
    {
      variety: "MAD JACK",
      contents: "2/BOX",
      rate_per_unit: 1333.0,
      quantity: "1 BOX",
      amount: 1333.0,
    },
    {
      variety: "COMMANDO",
      contents: "2/BOX",
      rate_per_unit: 1333.0,
      quantity: "1 BOX",
      amount: 1333.0,
    },
  ],
  double_ball_colour_crackling_2_pieces_mix: [
    {
      variety: "HOT & SWEET",
      contents: "2/BOX",
      rate_per_unit: 1580.0,
      quantity: "1 BOX",
      amount: 1580.0,
    },
    {
      variety: "TRUE LIES",
      contents: "2/BOX",
      rate_per_unit: 1580.0,
      quantity: "1 BOX",
      amount: 1580.0,
    },
    {
      variety: "JACK & JILL",
      contents: "2/BOX",
      rate_per_unit: 1580.0,
      quantity: "1 BOX",
      amount: 1580.0,
    },
    {
      variety: "RUF & TUF",
      contents: "2/BOX",
      rate_per_unit: 1580.0,
      quantity: "1 BOX",
      amount: 1580.0,
    },
    {
      variety: "DAY & NIGHT",
      contents: "2/BOX",
      rate_per_unit: 1580.0,
      quantity: "1 BOX",
      amount: 1580.0,
    },
    {
      variety: "BLACK & WHITE",
      contents: "2/BOX",
      rate_per_unit: 1580.0,
      quantity: "1 BOX",
      amount: 1580.0,
    },
  ],
  three_different_functions_13_x_2_5: [
    {
      variety: "3 Idiots Multicolour & crackling",
      contents: "3's box",
      rate_per_unit: 507.0,
      quantity: "1 BOX",
      amount: 507.0,
    },
    {
      variety: "3 Demons Multicolour & crackling",
      contents: "3's box",
      rate_per_unit: 507.0,
      quantity: "1 BOX",
      amount: 507.0,
    },
    {
      variety: "3-D Marvel Multicolour & crackling",
      contents: "3's box",
      rate_per_unit: 507.0,
      quantity: "1 BOX",
      amount: 507.0,
    },
    {
      variety: "Rang 3-Basanthi Multicolour & crackling",
      contents: "3's box",
      rate_per_unit: 507.0,
      quantity: "1 BOX",
      amount: 507.0,
    },
    {
      variety: "Brake-3-Dance Multicolour & crackling",
      contents: "3's box",
      rate_per_unit: 507.0,
      quantity: "1 BOX",
      amount: 507.0,
    },
    {
      variety: "Tricky Triplet Multicolour & crackling",
      contents: "3's box",
      rate_per_unit: 507.0,
      quantity: "1 BOX",
      amount: 507.0,
    },
    {
      variety: "Triple Sundae Multicolour & crackling",
      contents: "3's box",
      rate_per_unit: 507.0,
      quantity: "1 BOX",
      amount: 507.0,
    },
    {
      variety: "Naughty Night Multicolour & crackling",
      contents: "3's box",
      rate_per_unit: 507.0,
      quantity: "1 BOX",
      amount: 507.0,
    },
    {
      variety: "Crackling Cookies Full crackling",
      contents: "3's box",
      rate_per_unit: 507.0,
      quantity: "1 BOX",
      amount: 507.0,
    },
  ],
  repeating_aerial_items: [
    {
      variety: "LOVE DOSE (6 Multicolour shots & crakling",
      contents: "1 / BOX",
      rate_per_unit: 117.0,
      quantity: "1 BOX",
      amount: 117.0,
    },
    {
      variety: "12 COLOUR RIDER / CRACKLING",
      contents: "1 / BOX",
      rate_per_unit: 208.0,
      quantity: "1 box",
      amount: 208.0,
    },
    {
      variety: "12 COLOR 12 SHOT (Pandaseries-3varity)",
      contents: "1 / BOX",
      rate_per_unit: 159.0,
      quantity: "1 BOX",
      amount: 159.0,
    },
    {
      variety: "12 CRAZY MULTICOLOUR",
      contents: "1 / BOX",
      rate_per_unit: 286.0,
      quantity: "1 BOX",
      amount: 286.0,
    },
    {
      variety: "15 JUMBO BOX / 16 CRAZY",
      contents: "1 / BOX",
      rate_per_unit: 338.0,
      quantity: "1 BOX",
      amount: 338.0,
    },
    {
      variety: "25 Multi colour shots WITH CRACKLING",
      contents: "1 / BOX",
      rate_per_unit: 468.0,
      quantity: "1 BOX",
      amount: 468.0,
    },
    {
      variety: "30 CRAZY MULTICOLOUR SHOTS",
      contents: "1 / BOX",
      rate_per_unit: 651.0,
      quantity: "1 BOX",
      amount: 651.0,
    },
    {
      variety: "50 Multi Colour Shots with Crackling",
      contents: "1/box",
      rate_per_unit: 910.0,
      quantity: "1 box",
      amount: 910.0,
    },
    {
      variety: "50 FORTUNE (Multi colour with crackling)",
      contents: "1/BOX",
      rate_per_unit: 1235.0,
      quantity: "1 BOX",
      amount: 1235.0,
    },
    {
      variety: "60 CRAZY (Multi Colour Shots)",
      contents: "1 / BOX",
      rate_per_unit: 1296.0,
      quantity: "1 BOX",
      amount: 1296.0,
    },
    {
      variety: "60 SPARTA (Multi colour with crackling)",
      contents: "1 / BOX",
      rate_per_unit: 1450.0,
      quantity: "1 BOX",
      amount: 1450.0,
    },
    {
      variety: "120 CRAZY MULTICOLOUR SHOTS",
      contents: "1 / BOX",
      rate_per_unit: 2607.0,
      quantity: "1 BOX",
      amount: 2607.0,
    },
    {
      variety: "120 SHAADI Multicolour with crackling",
      contents: "1 / BOX",
      rate_per_unit: 2763.0,
      quantity: "1 BOX",
      amount: 2763.0,
    },
    {
      variety: "240 DREAM (Multi Colour with crackling)/ MORI TILAK",
      contents: "1 / BOX",
      rate_per_unit: 5428.0,
      quantity: "1 BOX",
      amount: 5428.0,
    },
  ],
  matches_and_caps: [
    {
      variety: "ROLL CAP",
      contents: "100s box",
      rate_per_unit: 91.0,
      quantity: "1 BOX",
      amount: 91.0,
    },
    {
      variety: "Colour Matches GEMS 'GLOBE'",
      contents: "10s box",
      rate_per_unit: 111.0,
      quantity: "10 Boxes/pkt",
      amount: 1110.0,
    },
    {
      variety: "Colour Matches LAMBHA 'GLOBE'",
      contents: "10's box",
      rate_per_unit: 150.0,
      quantity: "10BOX/box",
      amount: 1500.0,
    },
    {
      variety: "Colour Matches MEGA 'GLOBE'",
      contents: "10's box",
      rate_per_unit: 254.0,
      quantity: "10BOX/box",
      amount: 2540.0,
    },
  ],
};

export default firecrackerData;
